# Makefile - GNU make makefile for bashable

ALL=assert.sh trace.sh package.sh

all :
	echo "#!/bin/bash" > bashable.sh
	echo "# Do not edit: generated by Makefile." >> bashable.sh
	cat $(ALL) >> bashable.sh

test : all
	bash test.sh
